#!/usr/bin/env bash
#Prints bad luck in three contries
c=1
while [ $c -lt 21 ]; do
	case $c in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		*) echo $c;;
	esac
	(( c++ ))
done
